import { createContext, useContext, useState } from 'react';

// ⚠️ NATIVE-SPEAKER VERIFICATION REQUIRED
// All Amharic (AM) strings below were machine-translated and have NOT been
// reviewed by a native Amharic speaker. Before public launch, every string in
// the AM object must be verified and corrected by a native speaker — especially
// financial/business terminology, verb forms, and formal/informal register.
// Do NOT ship to production without completing this review.

const EN = {
  appName: 'ገበያ',
  loading: 'Loading your notebook…',
  today: 'Today',
  todayLabel: 'ዛሬ',
  credit: 'Credit',
  creditLabel: 'ብድር',
  report: 'Report',
  settings: 'Settings',
  sales: 'Sales',
  spent: 'Spent',
  iSold: 'I Sold',
  iSoldLabel: 'ሸጠሁ',
  iSpent: 'I Spent',
  iSpentLabel: 'ወጪ',
  creditBtn: 'Credit',
  creditBtnLabel: 'ብድር',
  calc: 'Calc',
  todaysEntries: "Today's Entries",
  noEntries: 'No entries yet. Use the buttons above to start!',
  profit: 'profit',
  edited: 'edited',
  editEntry: 'Edit entry',
  deleteEntryLabel: 'Delete entry',
  calculator: 'Profit Calculator',
  calcCost: 'Cost Price',
  calcSell: 'Selling Price',
  calcProfit: 'Profit',
  calcMargin: 'Margin',
  calcPlaceholder: 'Enter amount…',
  topProducts: 'Top Sold Today',
  weekTrend: '7-Day Trend',
  shareReport: 'Share Report',
  shareReportBtn: 'Share Today',
  shareTitle: 'Share Daily Report',
  shareDailyReport: 'Daily Report',
  shareTopItems: 'Top Items Sold',
  shareSentVia: 'Sent via ገበያ (Gebya)',
  shareViaDevice: 'Share via Device',
  openTelegram: 'Open in Telegram',
  copyText: 'Copy Text',
  usageInsights: 'Usage Insights',
  dayStreak: 'day streak',
  best: 'best',
  daysActive: 'days active',
  since: 'since',
  totalEntries: 'entries',
  sessions: 'sessions opened',
  shareMyStats: 'Share My Stats 📤',
  copiedToClipboard: 'Copied to clipboard!',
  shopProfile: 'Profile',
  userName: 'Name',
  phoneNumber: 'Phone Number',
  phoneRequired: 'Phone number is required',
  phoneInvalid: '9 digits starting with 7 or 9',
  telegramLabel: 'Telegram / Contact',
  telegramPlaceholder: '@username or phone (for Telegram share)',
  saveChanges: 'Save Changes',
  saved: 'Saved!',
  privacy: 'Privacy',
  hideAmounts: 'Hide amounts',
  totalsHidden: 'Totals are hidden — tap to show',
  totalsVisible: 'Totals are visible — tap to hide',
  paymentMethods: 'Payment Methods',
  banks: 'Banks',
  mobileWallets: 'Mobile Wallets',
  onlyEnabled: 'Only enabled methods appear as options in the form',
  recurringExpenses: 'Recurring Expenses',
  recurringHint: 'Quick-fill shortcuts for expenses you enter often',
  addRecurring: 'Add recurring expense',
  cancel: 'Cancel',
  add: 'Add',
  yourData: 'Your Data',
  storedOnDevice: 'Stored on this device',
  exportCSV: 'Export to CSV',
  exportHint: 'Download a spreadsheet backup',
  clearAll: 'Clear all data',
  clearHint: 'Permanently deletes everything — export first!',
  about: 'About',
  privacyNote: 'Your data never leaves this device. No account needed.',
  worksOffline: 'Works offline · Data stays on your phone · Free',
  achievementBadges: 'Achievement Badges',
  badgesEarned: 'earned',
  noBadges: 'Complete milestones to earn badges!',
  clearConfirm: 'Clear all data?',
  clearConfirmMsg: 'This will permanently delete all {count} entries and {credits} credit records. This cannot be undone.',
  yesDelete: 'Yes, delete everything',
  dataCleared: 'Data cleared',
  reloading: 'Reloading…',
  deleteEntry: 'Delete this entry?',
  delete: 'Delete',
  newBestDay: '🏆 New best day!',
  birr: 'birr',
  daily: 'Daily',
  weekly: 'Weekly',
  monthly: 'Monthly',
  expenseName: 'Expense name (e.g. Rent)',
  amount: 'Amount',
  sun: 'Sun', mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat',

  onboardWelcome: 'Welcome!',
  onboardSubtitle: 'Your business notebook',
  onboardTagline: 'የሱቅ ማስታወሻ ደብተር',
  onboardDesc: "Let's set up your profile. You can change these any time in Settings.",
  onboardNamePlaceholder: 'e.g. Tigist',
  onboardGetStarted: 'ጀምር — Get Started',
  onboardSettingUp: 'Setting up…',
  onboardFooter: 'All data stays on your phone · No account needed · Free',

  iSoldSomething: 'I Sold Something',
  iSpentSomething: 'I Spent Something',
  recordCredit: 'Record Credit',
  whatDidYouSell: 'What did you sell?',
  sellPlaceholder: 'e.g. bread, sugar…',
  whatDidYouSpendOn: 'What did you spend on?',
  spendPlaceholder: 'e.g. transport, rent…',
  creditNameLabel: 'Name',
  creditNamePlaceholder: 'e.g. Abebe…',
  howMuchTotal: 'How much total?',
  saveSale: 'Save Sale',
  saveExpense: 'Save Expense',
  saveCredit: 'Save Credit',
  addAnotherSale: 'Add another sale',
  addAnotherExpense: 'Add another expense',
  done: 'Done',
  birrSaved: 'birr saved',
  howMany: 'How many?',
  direction: 'Direction',
  theyOweMe: 'They owe me',
  iOweThem: 'I owe them',
  owesMe: 'ያበደርኩት',
  iOweLabel: 'የተበደርኩት',
  quickFill: 'Quick-fill',
  phoneOptional: 'Phone number',
  phoneOptionalHint: '(optional)',
  phonePlaceholder: 'e.g. 0912345678',
  whenDue: 'When is it due?',
  pickDate: 'Pick a date',
  selectDueDate: 'Please select a due date',
  advancedOptional: 'Advanced (optional)',
  whatDidYouPay: 'What did you pay for this?',
  perUnit: '(per unit)',
  helpsSeeProfit: 'Optional — helps you see your true profit',
  sellingBelowCost: 'You are selling below cost. You may lose money on this sale.',
  profitOnSale: 'Profit on this sale:',
  paymentType: 'Payment type',
  cash: 'Cash',
  bank: 'Bank',
  wallet: 'Wallet',

  editSale: 'Edit Sale',
  editExpense: 'Edit Expense',
  editCredit: 'Edit Credit',
  editEntryLabel: 'Edit Entry',
  editedAt: 'Edited',
  item: 'Item',
  quantity: 'Quantity',
  dueDate: 'Due date',
  costPriceLabel: 'Cost price',
  sellingBelowCostShort: 'Selling below cost.',
  profitLabel: 'Profit:',
  saving: 'Saving…',

  todaysProfit: "Today's Profit",
  todaysSales: "Today's Sales",
  salesLabel: 'Sales',
  expenses: 'Expenses',
  costOfGoods: 'Cost of goods',
  netProfit: 'Net Profit',
  advancedHint: 'Tap "Advanced" when recording a sale to see true profit',

  tapToReveal: 'Tap to reveal',
  tapToRevealAria: 'Tap to reveal amount',
  hideAmountAria: 'Hide amount',

  byDay: 'By Day',
  byWeek: 'By Week',
  noRecords: 'No records yet',
  startRecording: 'Record your first sale or expense to start',
  entries: 'entries',
  revenue: 'revenue',
  thisWeek: 'This Week',

  noCreditRecords: 'No credit records',
  addCreditHint: 'Tap "ብድር" on the Today tab to add one',
  owedToMe: 'Owed to me',
  iOweAmount: 'I owe',
  active: 'active',
  paid: 'paid',
  activeTab: 'Active',
  paidTab: 'Paid',
  noPaidRecords: 'No paid records yet',
  allCaughtUp: 'All caught up!',
  paidInFull: 'Paid in full',
  paidLabel: 'PAID',
  due: 'Due',
  owesMeLabel: 'Owes me',
  iOweTag: 'I owe',

  backToCredit: 'Back to ብድር',
  originalDebt: 'Original debt',
  amountPaid: 'Amount paid',
  stillOwes: 'Still owes',
  progress: 'Progress',
  percentPaid: '% paid',
  paidSome: 'Paid Some',
  allPaid: 'All Paid',
  call: 'Call',
  recordPartialPayment: 'Record Partial Payment',
  recordPayment: 'Record Payment',
  paymentHistory: 'Payment history',
  borrowed: 'Borrowed',
  paidBack: 'Paid back',
  remaining: 'Remaining',

  voiceNotSupported: 'Voice not supported — use keyboard',
  voiceInput: 'Voice input',
  tryAgain: 'Try again',

  close: 'Close',
};

const AM = {
  appName: 'ገበያ',
  loading: 'ማስታወሻ እየጫነ…',
  today: 'ዛሬ',
  todayLabel: 'ዛሬ',
  credit: 'ብድር',
  creditLabel: 'ብድር',
  report: 'ሪፖርት',
  settings: 'ቅንብሮች',
  sales: 'ሽያጭ',
  spent: 'ወጪ',
  iSold: 'ሸጠሁ',
  iSoldLabel: 'ሸጠሁ',
  iSpent: 'ወጪ',
  iSpentLabel: 'ወጪ',
  creditBtn: 'ብድር',
  creditBtnLabel: 'ብድር',
  calc: 'ሒሳብ',
  todaysEntries: 'የዛሬ ግቤቶች',
  noEntries: 'እስካሁን ምንም ግቤት የለም። ለመጀመር ከላይ ያሉትን ቁልፎች ይጠቀሙ!',
  profit: 'ትርፍ',
  edited: 'ተስተካክሏል',
  editEntry: 'ግቤት አስተካክል',
  deleteEntryLabel: 'ግቤት ሰርዝ',
  calculator: 'የትርፍ ካልኩሌተር',
  calcCost: 'የዋጋ ቅናሽ',
  calcSell: 'የሽያጭ ዋጋ',
  calcProfit: 'ትርፍ',
  calcMargin: 'ትርፍ (%)',
  calcPlaceholder: 'መጠን ያስገቡ…',
  topProducts: 'ዛሬ ምርጥ ሽያጭ',
  weekTrend: 'የ7 ቀን አዝማሚያ',
  shareReport: 'ሪፖርት አጋራ',
  shareReportBtn: 'ዛሬን አጋራ',
  shareTitle: 'ዕለታዊ ሪፖርት አጋራ',
  shareDailyReport: 'ዕለታዊ ሪፖርት',
  shareTopItems: 'ምርጥ ሽያጭ',
  shareSentVia: 'በ ገበያ (Gebya) ተልኳል',
  shareViaDevice: 'በስልክ አጋራ',
  openTelegram: 'ቴሌግራም ክፈት',
  copyText: 'ጽሑፍ ቅዳ',
  usageInsights: 'የአጠቃቀም ዝርዝር',
  dayStreak: 'ቀን ተከታታይ',
  best: 'ምርጥ',
  daysActive: 'ንቁ ቀናት',
  since: 'ጀምሮ',
  totalEntries: 'ግቤቶች',
  sessions: 'ክፍለ ጊዜ',
  shareMyStats: 'ስታቲስቲክሴን አጋራ 📤',
  copiedToClipboard: 'ተቀድቷል!',
  shopProfile: 'መገለጫ',
  userName: 'ስም',
  phoneNumber: 'ስልክ ቁጥር',
  phoneRequired: 'ስልክ ቁጥር ያስፈልጋል',
  phoneInvalid: '9 አሃዞች በ7 ወይም 9 የሚጀምሩ',
  telegramLabel: 'ቴሌግራም / ግንኙነት',
  telegramPlaceholder: '@username ወይም ስልክ',
  saveChanges: 'ለውጦችን አስቀምጥ',
  saved: 'ተቀምጧል!',
  privacy: 'ግላዊነት',
  hideAmounts: 'ቁጥሮችን ደብቅ',
  totalsHidden: 'ጠቅላላዎቹ ተደብቀዋል — ለማሳየት ተጭኑ',
  totalsVisible: 'ጠቅላላዎቹ ይታያሉ — ለመደበቅ ተጭኑ',
  paymentMethods: 'የክፍያ ዘዴዎች',
  banks: 'ባንኮች',
  mobileWallets: 'ሞባይል ዋሌት',
  onlyEnabled: 'የነቁ ዘዴዎች ብቻ በቅጹ ውስጥ ይታያሉ',
  recurringExpenses: 'ተደጋጋሚ ወጪዎች',
  recurringHint: 'ብዙ ጊዜ ለሚያስገቡዋቸው ወጪዎች ፈጣን ቅጽ',
  addRecurring: 'ተደጋጋሚ ወጪ አክል',
  cancel: 'ሰርዝ',
  add: 'አክል',
  yourData: 'ያንዎ ውሂብ',
  storedOnDevice: 'በዚህ ስልክ ላይ ተቀምጧል',
  exportCSV: 'CSV ወደ ውጭ ላክ',
  exportHint: 'ሰነድ ምትኬ ያውርዱ',
  clearAll: 'ሁሉንም ውሂብ አጥፋ',
  clearHint: 'ሁሉም ነገር ሙሉ በሙሉ ይሰረዛል — መጀመሪያ ይልኩ!',
  about: 'ስለ ፕሮግራሙ',
  privacyNote: 'ውሂቡ ከዚህ ስልክ አይወጣም። ምዝገባ አያስፈልግም።',
  worksOffline: 'ያለ ኢንተርኔት ይሰራል · ውሂቡ በስልክዎ ላይ ይቆያል · ነፃ',
  achievementBadges: 'የስኬት ባጆች',
  badgesEarned: 'ተገኝቷል',
  noBadges: 'ባጆች ለማግኘት ኢላማዎቹን ያሟሉ!',
  clearConfirm: 'ሁሉንም ውሂብ አጥፋ?',
  clearConfirmMsg: 'ይህ ሁሉን {count} ግቤቶችና {credits} የብድር መዝገቦችን ሙሉ በሙሉ ይሰርዛል። ሊቀለበስ አይችልም።',
  yesDelete: 'አዎ፣ ሁሉንም ሰርዝ',
  dataCleared: 'ውሂቡ ተሰርዟል',
  reloading: 'እንደገና እየጫነ…',
  deleteEntry: 'ይህን ግቤት ትሰርዛለህ?',
  delete: 'ሰርዝ',
  newBestDay: '🏆 አዲስ ምርጥ ቀን!',
  birr: 'ብር',
  daily: 'ዕለታዊ',
  weekly: 'ሳምንታዊ',
  monthly: 'ወርሃዊ',
  expenseName: 'የወጪ ስም (ለምሳሌ ኪራይ)',
  amount: 'መጠን',
  sun: 'እሁድ', mon: 'ሰኞ', tue: 'ማክሰ', wed: 'ረቡዕ', thu: 'ሐሙስ', fri: 'አርብ', sat: 'ቅዳሜ',

  onboardWelcome: 'እንኳን ደህና መጡ!',
  onboardSubtitle: 'Your business notebook',
  onboardTagline: 'የሱቅ ማስታወሻ ደብተር',
  onboardDesc: 'መገለጫዎን እናዘጋጅ። በማንኛውም ጊዜ በቅንብሮች ውስጥ መቀየር ይችላሉ።',
  onboardNamePlaceholder: 'ለምሳሌ ትግስት',
  onboardGetStarted: 'ጀምር — Get Started',
  onboardSettingUp: 'እየተዘጋጀ…',
  onboardFooter: 'ውሂቡ በስልክዎ ላይ ይቆያል · ምዝገባ አያስፈልግም · ነፃ',

  iSoldSomething: 'ሸጠሁ',
  iSpentSomething: 'ወጪ',
  recordCredit: 'ብድር መዝግብ',
  whatDidYouSell: 'ምን ሸጡ?',
  sellPlaceholder: 'ለምሳሌ ዳቦ፣ ስኳር…',
  whatDidYouSpendOn: 'ምን ላይ ወጪ?',
  spendPlaceholder: 'ለምሳሌ ትራንስፖርት፣ ኪራይ…',
  creditNameLabel: 'ስም',
  creditNamePlaceholder: 'ለምሳሌ አበበ…',
  howMuchTotal: 'ጠቅላላ ስንት?',
  saveSale: 'ሽያጭ አስቀምጥ',
  saveExpense: 'ወጪ አስቀምጥ',
  saveCredit: 'ብድር አስቀምጥ',
  addAnotherSale: 'ሌላ ሽያጭ አክል',
  addAnotherExpense: 'ሌላ ወጪ አክል',
  done: 'ተጠናቀቀ',
  birrSaved: 'ብር ተቀምጧል',
  howMany: 'ስንት?',
  direction: 'አቅጣጫ',
  theyOweMe: 'ያበደርኩት',
  iOweThem: 'የተበደርኩት',
  owesMe: 'ያበደርኩት',
  iOweLabel: 'የተበደርኩት',
  quickFill: 'ፈጣን ሙላ',
  phoneOptional: 'ስልክ ቁጥር',
  phoneOptionalHint: '(ምርጫ)',
  phonePlaceholder: 'ለምሳሌ 0912345678',
  whenDue: 'መቼ ይከፈላል?',
  pickDate: 'ቀን ምረጥ',
  selectDueDate: 'የክፍያ ቀን ይምረጡ',
  advancedOptional: 'ተጨማሪ (ምርጫ)',
  whatDidYouPay: 'ለዚህ ምን ከፈሉ?',
  perUnit: '(በአንድ)',
  helpsSeeProfit: 'ምርጫ — ትክክለኛውን ትርፍ ለማየት ይረዳል',
  sellingBelowCost: 'ከዋጋ በታች እየሸጡ ነው። ኪሳራ ሊደርስ ይችላል።',
  profitOnSale: 'በዚህ ሽያጭ ትርፍ:',
  paymentType: 'የክፍያ አይነት',
  cash: 'ጥሬ ገንዘብ',
  bank: 'ባንክ',
  wallet: 'ዋሌት',

  editSale: 'ሽያጭ አስተካክል',
  editExpense: 'ወጪ አስተካክል',
  editCredit: 'ብድር አስተካክል',
  editEntryLabel: 'ግቤት አስተካክል',
  editedAt: 'ተስተካክሏል',
  item: 'ዕቃ',
  quantity: 'ብዛት',
  dueDate: 'የክፍያ ቀን',
  costPriceLabel: 'የዋጋ',
  sellingBelowCostShort: 'ከዋጋ በታች።',
  profitLabel: 'ትርፍ:',
  saving: 'እየተቀመጠ…',

  todaysProfit: 'የዛሬ ትርፍ',
  todaysSales: 'የዛሬ ሽያጭ',
  salesLabel: 'ሽያጭ',
  expenses: 'ወጪዎች',
  costOfGoods: 'የዕቃ ዋጋ',
  netProfit: 'ንጹህ ትርፍ',
  advancedHint: 'ትክክለኛውን ትርፍ ለማየት ሽያጭ ሲመዘግቡ "ተጨማሪ" ተጭኑ',

  tapToReveal: 'ለማሳየት ተጭኑ',
  tapToRevealAria: 'መጠንን ለማሳየት ተጭኑ',
  hideAmountAria: 'መጠንን ደብቅ',

  byDay: 'በቀን',
  byWeek: 'በሳምንት',
  noRecords: 'እስካሁን ምንም መዝገብ የለም',
  startRecording: 'ለመጀመር የመጀመሪያ ሽያጭ ወይም ወጪ ይመዝግቡ',
  entries: 'ግቤቶች',
  revenue: 'ገቢ',
  thisWeek: 'ይህ ሳምንት',

  noCreditRecords: 'የብድር መዝገብ የለም',
  addCreditHint: 'ብድር ለማክል በዛሬ ገጽ ላይ "ብድር" ተጭኑ',
  owedToMe: 'ያበደርኩት',
  iOweAmount: 'የተበደርኩት',
  active: 'ንቁ',
  paid: 'የተከፈለ',
  activeTab: 'ንቁ',
  paidTab: 'የተከፈለ',
  noPaidRecords: 'እስካሁን የተከፈለ መዝገብ የለም',
  allCaughtUp: 'ሁሉም ተከፍሏል!',
  paidInFull: 'ሙሉ ተከፍሏል',
  paidLabel: 'ተከፍሏል',
  due: 'ክፍያ',
  owesMeLabel: 'ያበደርኩት',
  iOweTag: 'የተበደርኩት',

  backToCredit: 'ወደ ብድር ተመለስ',
  originalDebt: 'ዋና ዕዳ',
  amountPaid: 'የተከፈለ',
  stillOwes: 'ቀሪ ዕዳ',
  progress: 'ሂደት',
  percentPaid: '% ተከፍሏል',
  paidSome: 'ከፊል ክፍያ',
  allPaid: 'ሙሉ ተከፍሏል',
  call: 'ደውል',
  recordPartialPayment: 'ከፊል ክፍያ መዝግብ',
  recordPayment: 'ክፍያ መዝግብ',
  paymentHistory: 'የክፍያ ታሪክ',
  borrowed: 'የተበደረ',
  paidBack: 'የተመለሰ',
  remaining: 'ቀሪ',

  voiceNotSupported: 'ድምጽ አይደገፍም — የቁልፍ ሰሌዳ ይጠቀሙ',
  voiceInput: 'ድምጽ',
  tryAgain: 'እንደገና ሞክር',

  close: 'ዝጋ',
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('gebya_lang') || 'en');

  const toggleLang = () => {
    setLang(prev => {
      const next = prev === 'en' ? 'am' : 'en';
      localStorage.setItem('gebya_lang', next);
      return next;
    });
  };

  const t = lang === 'am' ? AM : EN;

  return (
    <LangContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
